### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by TheSeanLavery** [TheSeanLavery/code-review-gpt#17]
There should be a depedencies.txt. Probably also have an installer.py as well. What are some best practices?

**Comment by CodeReviewGPT** [comment]
Great question! Dependencies.txt is a useful way to keep track of the packages and modules that are needed for a project to run properly. It's also helpful for other developers who may be working on the project to be able to quickly understand what is needed to get the project up and running.

An installer.py script can also be helpful. This script can automate the process of installing any necessary dependencies, as well as setting up the environment and providing any additional setup instructions that may be necessary.

As far as best practices go, it's important to make sure that the dependencies.txt is kept up to date with any changes so that all developers are always working with the most recent version. Additionally, it's important to ensure that the installer.py script is easy to follow and understand, as this will make it easier for developers to get up and running quickly.

**Comment by TheSeanLavery** [comment]
Can you create a Depedencies.txt for these?
import requests
import configparser
import openai

**Comment by CodeReviewGPT** [comment]
Sure! Here is the dependencies.txt file:

requests==2.25.0
configparser==4.0.2
openai==2.1.0
